//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digimap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigimapEntitiesFinal : DbContext
    {
        public DigimapEntitiesFinal()
            : base("name=DigimapEntitiesFinal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PtoIntere> PtoInteres { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
