//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digimap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtoIntere
    {
        public string id_Interes { get; set; }
        public string nom_Punto { get; set; }
        public string instruccion_uno { get; set; }
        public string instruccion_dos { get; set; }
        public string instruccion_tres { get; set; }
        public string path { get; set; }
    }
}
